### ISSUE TITLE
Mention middleware order in README

### ISSUE THREAD

**Issue by IvanUkhov** [mperham/rack-fiber_pool#1]
If I get it right, this middleware should be used before CookieStore in case of Rails, but there is no a signle line about it in README.

<pre>
ActionController::Dispatcher.middleware.insert_before ActionController::Session::CookieStore, Rack::FiberPool
</pre>

Without specifying the order of middlewares, session does not work for me. Always InvalidAuthenticityToken, etc.

**Comment by mperham** [comment]
Updated readme.
