### ISSUE TITLE
server timeout changes when using fiber pool

### ISSUE THREAD

**Issue by bmidgley** [mperham/rack-fiber_pool#18]
Using sinatra/thin. We have a couple of long-running server actions, but after installing the fiber pool, anything that takes more than 30s results in the client being disconnected and given an empty response.

Where do I look to see where that 30s might be set? Why would a rack change cause that?

**Comment by JoshMcKin** [comment]
Pretty sure fiber_pool does not set a timeout. Its probably thin.

**Comment by bmidgley** [comment]
Right, it was in thin. I think the reason it didn't stop before is our long running action was blocking everything else including the timeout.
