### ISSUE TITLE
Size of fiber pool should be configurable

### ISSUE THREAD

**Issue by igrigorik** [mperham/rack-fiber_pool#3]
<pre>
 @fiber_pool = ::FiberPool.new
</pre>

That creates a pool of max size 100. Just doing some testing on this side with a simple sleep query and this is the actual bottleneck in throughput. I'm thinking the size should be configurable when you include the middleware?

**Comment by mperham** [comment]
Pull requests accepted.  See Rails' CookieStore for example.

**Comment by maccman** [comment]
I'd love to see this feature included

**Comment by JoshMcKin** [comment]
Would adding Rack::FiberPool::SIZE = 250 to the environment.rb file of a Rails3 app be the correct location for setting pool size?

**Comment by mperham** [comment]
Josh, I don't want to advise you on how to override constants - it's a terrible hack.  I'll see if I can implement something proper when I am working on OSS next.

**Comment by JoshMcKin** [comment]
Word. Guess I'll can just unpack it and change it in the code. Looking forward to the update.

**Comment by mperham** [comment]
I've implemented the change but still need to write some testing infrastructure before I plan on releasing a new gem.

**Comment by mperham** [comment]
Just pushed 0.9.1

**Comment by JoshMcKin** [comment]
awesome, thanks.
